name: Bug
description: Reporting bugs you encounter
title: Describe the bug you encountered concisely
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        For reproducability and debuggability, please fill in the form according to the requirements
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the scenario in which the issue occurs
      placeholder: |
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: JavSPn Config
      description: Paste your config here
      placeholder: |
    validations:
      required: true
        - Please attach your `config.ini`
  - type: dropdown
    id: proxy
    attributes:
      label: Proxy
      description: Are you using a proxy?
      options:
        - Yes
        - No
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log
      description: Please paste the content of `JavSP.log` here.
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot(optional)
      description: Providing a screenshot will help me resolve the issue.
  - type: checkboxes
    id: promise
    attributes:
      label: Confirmation
      description: Before openning a new issue, please confirm you're using the latest version of [JavSPn](https://github.com/Yuukiy/JavSP/releases/latest).
      options:
        - label: I can confirm that I'm using the latest version of JavSPn.
          required: true
