name: Feature request
description: A request for new features
title: Summary your feature request here
labels: ["feature", "triage"]
body:
  - type: textarea
    id: what-you-want
    attributes:
      label: Feature request
      placeholder: |
        Describe your feature request here. 
        If you have an implementation in mind, please tell me about it as well.
    validations:
      required: true
  - type: checkboxes
    id: promise
    attributes:
      label: Confirmation
      description: Before openning a new issue, please confirm you're using the latest version of [JavSPn](https://github.com/Yuukiy/JavSP/releases/latest).
      options:
        - label: I can confirm that I'm using the latest version of JavSPn.
          required: true
