# This is a basic workflow to help you get started with Actions

name: Cx_Freeze on Windows

# Controls when the workflow will run
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: glyh/JavSPn/.github/workflows/pull_dependencies.yml@master
    steps:
      - name: Build with Cx_Freeze for windows
        run: poetry run python setup.py build_exe -b dist

      - name: Switch code page
        run: |
          chcp 65001

      - name: Set VERSION variable for windows
        run: |
          echo "VERSION=$(poetry run python scripts/version.py)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: JavSPn-${{ env.VERSION }}-Windows-amd64
          path: dist
