# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Unit Test: web-based functions"

on:
  push:
    branches:
    - master
    - premerge
    - JavSPn
  pull_request:
    branches:
    - master
    - premerge
    - JavSPn
  schedule:
  # Web crawlers might be outdated because of website updating, so run periodically to follow the changes
  - cron: '9 9 * * 3,6,0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-web-crawlers:

    runs-on: glyh/JavSPn/.github/workflows/pull_dependencies.yml@main
    steps:
    - name: Switch code page
      run: |
        chcp 65001
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3
    - name: Test proxyfree.py
      run: |
        poetry run pytest unittest/test_proxyfree.py
    - name: Test web crawlers
      run: |
        poetry run pytest unittest/test_crawlers.py
    - name: Upload log as artifact
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: JavSP-web-funcs.log
        path: javspn/JavSP.log
